### ISSUE TITLE
Crashes related to error logs, and a fix for the error itself

### ISSUE THREAD

**Issue by Halopend** [kevindew/Hue-Quick-Start-iOS-Swift#1]
Since I wanted to looking into making a hue app despite only being halfway though an swift developer course and have little coding experience, I thought this project would be a great jumping point (doing this all myself would of been a nightmare, though great learning experience I'm sure). 

Anyway, when attempting to change the lights my app crashes and given what xCode shows me it appears related to this code in the ControlLightsViewController.swift file:

```
    let errorsArr = errors as? [NSError]

    if errorsArr != nil {
      let message = String(format: NSLocalizedString("Errors", comment: ""), arguments: errorsArr!)

      NSLog("Response: \(message)")
    }
```

Not entirely sure how to fix it but 
http://ericasadun.com/2014/07/30/swift-these-took-far-longer-to-put-together-than-they-should-have/
seems relevant.

My attempt to implement what the site suggested did fix the crashing, but the error printouts weren't useful so I must not be using it quite right. 

Anyway, by printing the errors directly using println( ) i did find out where it was failing.

```
    lightState.hue = Int(Int(arc4random()) * maxHue)
```

should be

```
    lightState.hue = Int(Int(arc4random()) % maxHue)
```

**Comment by kevindew** [comment]
Super thanks for this too! I haven't got to run this code yet as other people in the house have been asleep when I've been writing it. I'll give it a spin tomorrow

**Comment by kevindew** [comment]
I've got this fixed now. Had a bit of a nightmare getting String(format) method working, think I've got it right now but not definite.
